### ISSUE TITLE
Sepa Credit Transfer - rejected by the bank - issue with xml content

### ISSUE THREAD

**Issue by dgouthiere** [OCA/bank-payment#170] opened 2015-05-29 14:49 UTC
Hi All, my name is David Gouthière - new joiner; I use Odoo to generate SCT payments and transfer xml to the bank for execution. It was my first trial, I made a real test with small amount ang get many severe issues. I had to manage the xml manually to get it loaded and executed by the bank.

I had to change to pain 03 instead of 05, and manually i had to fix somme tags in the header. to get the file accepted by the bank.
2 bugs are causing of the reject :
• 2 lines inverted in the header
• use of single quotes instaed of double quotes
As is
<?xml version='1.0' encoding='UTF-8'?>
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:iso:std:iso:20022:tech:xsd:pain.001.001.05">
To be
<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

Manually fixed, files has been accepted and executed.  The day after, examination of my daily statement has shown one more mistake.
Below, a rejected file and an accepted one, so you can compare, 
The accepted file have also caused an issue, you can check the effect in the statement below

Rejected file (by the bank)

sct_2015-005-DG-sprl.xml
<?xml version='1.0' encoding='UTF-8'?>
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:iso:std:iso:20022:tech:xsd:pain.001.001.05">
  <CstmrCdtTrfInitn>
    <GrpHdr>
      <MsgId>2015/004</MsgId>
      <CreDtTm>2015-05-28T16:08:40</CreDtTm>
      <NbOfTxs>1</NbOfTxs>
      <CtrlSum>1.21</CtrlSum>
      <InitgPty>
        <Nm>David Gouthiere sprl</Nm>
        <Id>
          <OrgId>
            <Othr>
              <Id>BE0894513115</Id>
              <Issr>KBO-BCE</Issr>
            </Othr>
          </OrgId>
        </Id>
      </InitgPty>
    </GrpHdr>
    <PmtInf>
      <PmtInfId>2015/004-20150528-NORM</PmtInfId>
      <PmtMtd>TRF</PmtMtd>
      <BtchBookg>false</BtchBookg>
      <NbOfTxs>1</NbOfTxs>
      <CtrlSum>1.21</CtrlSum>
      <PmtTpInf>
        <InstrPrty>NORM</InstrPrty>
        <SvcLvl>
          <Cd>SEPA</Cd>
        </SvcLvl>
      </PmtTpInf>
      <ReqdExctnDt>2015-05-28</ReqdExctnDt>
      <Dbtr>
        <Nm>David Gouthiere sprl</Nm>
      </Dbtr>
      <DbtrAcct>
        <Id>
          <IBAN>BE63143070432108</IBAN>
        </Id>
      </DbtrAcct>
      <DbtrAgt>
        <FinInstnId>
          <BICFI>GEBABEBB</BICFI>
        </FinInstnId>
      </DbtrAgt>
      <ChrgBr>SHAR</ChrgBr>
      <CdtTrfTxInf>
        <PmtId>
          <EndToEndId>036</EndToEndId>
        </PmtId>
        <Amt>
          <InstdAmt Ccy="EUR">1.21</InstdAmt>
        </Amt>
        <CdtrAgt>
          <FinInstnId>
            <BICFI>GKCCBEBB</BICFI>
          </FinInstnId>
        </CdtrAgt>
        <Cdtr>
          <Nm>David Gouthiere (prive)</Nm>
        </Cdtr>
        <CdtrAcct>
          <Id>
            <IBAN>BE58795551250379</IBAN>
          </Id>
        </CdtrAcct>
        <RmtInf>
          <Ustrd>Test1 filetsf avec Isabel</Ustrd>
        </RmtInf>
      </CdtTrfTxInf>
    </PmtInf>
  </CstmrCdtTrfInitn>
</Document>

Accepted and executed by the bank

sct_2015-006-DG-sprl2ok.xml
<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <CstmrCdtTrfInitn>
    <GrpHdr>
      <MsgId>2015/006</MsgId>
      <CreDtTm>2015-05-28T18:59:45</CreDtTm>
      <NbOfTxs>1</NbOfTxs>
      <CtrlSum>1.21</CtrlSum>
      <InitgPty>
        <Nm>David Gouthiere sprl</Nm>
        <Id>
          <OrgId>
            <Othr>
              <Id>0894513115</Id>
              <Issr>KBO-BCE</Issr>
            </Othr>
          </OrgId>
        </Id>
      </InitgPty>
    </GrpHdr>
    <PmtInf>
      <PmtInfId>2015/006-20150528-NORM</PmtInfId>
      <PmtMtd>TRF</PmtMtd>
      <BtchBookg>false</BtchBookg>
      <NbOfTxs>1</NbOfTxs>
      <CtrlSum>1.21</CtrlSum>
      <PmtTpInf>
        <InstrPrty>NORM</InstrPrty>
        <SvcLvl>
          <Cd>SEPA</Cd>
        </SvcLvl>
      </PmtTpInf>
      <ReqdExctnDt>2015-05-28</ReqdExctnDt>
      <Dbtr>
        <Nm>David Gouthiere</Nm>
      </Dbtr>
      <DbtrAcct>
        <Id>
          <IBAN>BE63143070432108</IBAN>
        </Id>
      </DbtrAcct>
      <DbtrAgt>
        <FinInstnId>
          <BIC>GEBEBEBB</BIC>
        </FinInstnId>
      </DbtrAgt>
      <ChrgBr>SLEV</ChrgBr>
      <CdtTrfTxInf>
        <PmtId>
          <EndToEndId>688105934715</EndToEndId>
        </PmtId>
        <Amt>
          <InstdAmt Ccy="EUR">1.21</InstdAmt>
        </Amt>
        <CdtrAgt>
          <FinInstnId>
            <BIC>GKCCBEBB</BIC>
          </FinInstnId>
        </CdtrAgt>
        <Cdtr>
          <Nm>David Gouthiere (prive)</Nm>
        </Cdtr>
        <CdtrAcct>
          <Id>
            <IBAN>BE58795551211111</IBAN>
          </Id>
        </CdtrAcct>
        <RmtInf>
          <Strd>
            <CdtrRefInf>
              <Tp>
                <CdOrPrtry>
                  <Cd>SCOR</Cd>
                </CdOrPrtry>
                <Issr>ISO</Issr>
              </Tp>
              <Ref>EXJ/2015/0008</Ref>
            </CdtrRefInf>
          </Strd>
        </RmtInf>
      </CdtTrfTxInf>
    </PmtInf>
  </CstmrCdtTrfInitn>
</Document>

Statement - the day after

![statement](https://cloud.githubusercontent.com/assets/12418198/7885021/ea831be0-0621-11e5-9caa-278156208b88.JPG)

Executed, but issues anyway because communication and references are inverted, as stated on the statement. I checked the xml, and the issue is well there (it is not a mistake of the bank)

It is a critical issue, because the beneficiary will not find its expected communication and will not be able to reconcile its customer payments.

Indeed, in the xml, we can see that  EXJ/2015/0008 is filled in the tag reserved for communication to beneficiary and the 688105934715 is filled into EndToEndId

Looking further, I also see that the xml is not exactly compliant with the rulebook - but here not rejected by this bank (could be by another one) : for this case, Odoo uses ISO instead Of BBA

<Issr>ISO</Issr>  :  ISO must be used when the Reference corresponds to an european Reference code (max 25 char)

In Belgium (only) this code must be BBA (Belgian Bank Association) and the value if <REF> tag must be  12 digit structured communication with check digit base on mod 97 (like old BBAN account 3-7-2). 

If not structured, the tag  <Ustrd> must be used in <RmtInf> 

Here the reference to get the right rules

https://www.febelfin.be/en/standards-distance-banking

(for security reason - i have change value of my own account nr in the xml ...)

I can just report this blocking issue, I am not able to fix it, beeing not a technician. please feel free to ask more questions.

**Comment by sbidoul** [comment] 2015-05-29 15:01
Hi David,

Regarding the BBA structured communication, the l10n_be_iso20022_pain module [1] should solve your issue.

Regarding the XML format, can you send me the files in private mail. I'll have a look.

**Comment by dgouthiere** [comment] 2015-05-29 15:04
Hi Stéphane,
i do it now, thanks for being so fast,
David

**Comment by sbidoul** [comment] 2015-05-29 15:12
Regarding the PAIN version 003, you can select it in the Export Type field of the Payment Mode.

**Comment by dgouthiere** [comment] 2015-05-29 15:15
Thx, it is what I did to produce my second file.

**Comment by sbidoul** [comment] 2015-05-29 15:36
Regarding the errors in the header, it is surprising because the xml declaration `<?xml...` as well as the namespace declaration emitted are valid xml and should be accepted.

Can you provide the exact error message provided by your bank?

**Comment by dgouthiere** [comment] 2015-05-29 16:03
ok, i do it via your email to paste images easier

**Comment by dgouthiere** [comment] 2015-05-29 16:12
Le 29/05/2015 17:36, Stéphane Bidoul (ACSONE) a écrit :

> Regarding the errors in the header, it is surprising because the xml 
> declaration |<?xml...| as well as the namespace declaration emitted 
> are valid xml and should be accepted.
> 
> Can you provide the exact error message provided by your bank?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/OCA/bank-payment/issues/170#issuecomment-106849186.

I cannot capture the message of the bank, but it just pop up :
- sct_2015-005 =>  attention aucun schéma n'a été trouvé
- sct_2015-006 =>  attention aucun schéma n'a été trouvé
- sct_2015-004 was rejected because he expected a ciri file - because
  I load a txt file instead of xml  (was my fault)

ensuite, j'ai reformaté le header comme mentionné dans les spec febelfin 
et c'est passé

bàv,
David

---

L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by dgouthiere** [comment] 2015-05-29 16:19
Le 29/05/2015 17:36, Stéphane Bidoul (ACSONE) a écrit :

> Regarding the errors in the header, it is surprising because the xml 
> declaration |<?xml...| as well as the namespace declaration emitted 
> are valid xml and should be accepted.
> 
> Can you provide the exact error message provided by your bank?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/OCA/bank-payment/issues/170#issuecomment-106849186.

Stéphane,

Here is the expected content of the header, from febelfin source.

When you look at the sent files, you will see the differences that I 
fixed manually,
Kind regards,
David

---

L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by sbidoul** [comment] 2015-06-15 10:08
Hello @dgouthiere,

I did some additional tests and so far I cannot reproduce the issues you mentioned:
- the XML header is compliant (the exact format of the XML declaration and namespace attributes in the febelfin spec is just an example and is not relevant, so both the version produced by the module and the version you adapted manually are correct)
- the structuered communication is correct according to the febelfin spec when you use l10n_be_iso20022_pain from OCA/l10n-belgium

So I'm closing this issue. If you feel there is still something incorrect, do not hesitate to reopen and provide additional information.

**Closed as completed by sbidoul** 2015-06-15 10:08 UTC

**Comment by dgouthiere** [comment] 2015-06-15 10:52
Le 15/06/2015 12:08, Stéphane Bidoul (ACSONE) a écrit :

> Hello @dgouthiere https://github.com/dgouthiere,
> 
> I did some additional tests and so far I cannot reproduce the issues 
> you mentioned:
> - the XML header is compliant (the exact format of the XML
>   declaration and namespace attributes in the febelfin spec is just
>   an example and is not relevant, so both the version produced by
>   the module and the version you adapted manually are correct)
> - the structuered communication is correct according to the febelfin
>   spec when you use l10n_be_iso20022_pain from OCA/l10n-belgium
> 
> So I'm closing this issue. If you feel there is still something 
> incorrect, do not hesitate to reopen and provide additional information.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/OCA/bank-payment/issues/170#issuecomment-112004467.
> 
> Hi Stéphane,

Thanks for feed-back !
Next week I will work on reinstalling my payment modules + the patch and 
will remake a real test with the bank.

I will keep you posted

Kind regards,
David

---

L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com
