### ISSUE TITLE
V12 Bug in the SEPA XML Payment file?

### ISSUE THREAD

**Issue by Binformed** [OCA/bank-payment#540] opened 2019-01-21 20:43 UTC
When I generate a SEPA Payment file it produces the following structure for the IBAN numbers:

<DbtrAcct>

        <Id>
              <Othr>        

                      <Id>NL52INGB0006989111</Id>
               </Othr>

         </Id>

</DbtrAcct>

While the bank import expects:

<DbtrAcct>

            <Id>

                   <IBAN>NL52INGB0006989111</IBAN>

            </Id>

</DbtrAcct>

Did anyone else ran into this issue, I cannot find any changes in the format in which the XML should be provided to the banks

**Comment by pedrobaeza** [comment] 2019-01-21 22:45
I don't think that's valid SEPA structure, and more putting this few information, as there are a lot of `<Id>`  tags across the whole file.

**Comment by javimurcia** [comment] 2019-01-25 22:22
I'm 99% sure this is caused by an invalid IBAN. I've seen this behavior when you try to generate a payment file against a bank account with an invalid IBAN (when the bank account has a type type of bank, instead of iban)

So Binformed, check your iban, and let us know if this fixes the issue.

TIP: when you are creating the bank account you can check if the iban is correct. If the iban is wrong, account type will be bank:
![image](https://user-images.githubusercontent.com/33467841/51775711-fc648300-20f6-11e9-8e04-5b134ee4a7ce.png)

If the IBAN is valid, it will show IBAN (as soon as is valid, there is no need to save the record):

![image](https://user-images.githubusercontent.com/33467841/51775767-2322b980-20f7-11e9-93d4-d1657d785350.png)

**Comment by pedrobaeza** [comment] 2019-01-26 00:40
Closing the issue as no answer and valid explanations are given.

**Closed as completed by pedrobaeza** 2019-01-26 00:40 UTC

**Comment by Binformed** [comment] 2019-01-26 08:40
Apologies for the late response. I was offline for a few days.

Seems that Crazy-Projects was completely right about their suggestion....many thanks for this....problem is indeed with the acc_type field. 

What we have noticed after installing the modules the field acc.type appears twice on the res.bank form. 
![image](https://user-images.githubusercontent.com/32832163/51784700-6d368a00-214d-11e9-8486-ce9d356e3926.png)

The field is added from the base view (res.partner.bank.form) as from an additional view (account_payment_mode.res_partner_bank_form) which is coming from account payment module (account_payment_mode/views/res_partner_bank.xml).

What we have also noticed is that the acc_type is not computed when you add a new bank number.

Thanks in advance for your thoughts.

**Comment by pedrobaeza** [comment] 2019-01-27 00:32
Fixed the double view of the field in https://github.com/OCA/bank-payment/commit/cd947b740aab004107662fd1141706ee3cdc7f6f

**Comment by Binformed** [comment] 2019-01-28 12:51
Thanks for fixing this in the view...but I think this needs to be fixed in model as well. acc_type field in standard Odoo:
![image](https://user-images.githubusercontent.com/32832163/51837408-9567e980-2303-11e9-8dd2-d745c8297fa9.png)

Field after installing payment module:

![image](https://user-images.githubusercontent.com/32832163/51837454-b597a880-2303-11e9-8064-956b949ddcdc.png)

It has changed from a selection to a char field.

**Comment by Binformed** [comment] 2019-01-28 15:42
I think this has to be commented as well
![image](https://user-images.githubusercontent.com/32832163/51847283-b2101b80-231b-11e9-91ba-ce28b3c895a2.png)

**Comment by pedrobaeza** [comment] 2019-02-02 01:00
You're right. Fixed in c16f0620
