### ISSUE TITLE
[12.0][BUG] account_payment_sale

### ISSUE THREAD

**Issue by florian-dacosta** [OCA/bank-payment#536] opened 2019-01-18 22:41 UTC
Hi
I have found a bug in module account_payment_sale, but I am not sure how to fix it nicely.
The payment_mode_id does not propagate from the sale order to the invoice. 
I guess the tests are a bit to naive, that is why they pass anyway.
Here we try to propagate the payment mode : https://github.com/OCA/bank-payment/blob/12.0/account_payment_sale/models/sale_order.py#L35
Here, the invoice is created with the right value (coming from the SO) : https://github.com/OCA/OCB/blob/12.0/addons/sale/models/sale.py#L521
And it is overriden here https://github.com/OCA/OCB/blob/12.0/addons/sale/models/sale.py#L570

I really don't get why they have refactored it this way, they create the invoice and then they override a lot of values...
And I do not really see a clean solution to solve this.
Any idea?

**Comment by pedrobaeza** [comment] 2019-01-19 08:45
Oh, that's very ugly by Odoo...

I suppose we have to override `action_invoice_create` method, and write again after calling super the value of the payment mode if differs from the one in the sale order.

**Comment by ThomasBinsfeld** [comment] 2019-03-01 10:00
@florian-dacosta @pedrobaeza Anything new about this? The problem is the same with the [mandate](https://github.com/OCA/bank-payment/pull/533).

**Comment by pedrobaeza** [comment] 2019-03-01 15:34
I'm afraid the bug is out there and we need to do the commented hack.

**Comment by sebalix** [comment] 2019-04-24 09:04
@florian-dacosta Hi, any news about this bug?

**Comment by florian-dacosta** [comment] 2019-04-24 09:11
Hi, I did not took the time to solve it, no.
Actually, I just found the bug when  migrating sale_automatic_workflow_payment_mode, but I do not use these modules in version 12 so it has not been my priority...
Also, I did not find a clean way to fix it...

**Comment by sebalix** [comment] 2019-04-24 09:14
@florian-dacosta thanks for the feedback! I'll try to fix it with the workaround proposed by @pedrobaeza.

**Comment by florian-dacosta** [comment] 2019-04-24 09:15
I was wondering if it was possible to propose a refactore to Odoo... But I guess it won't happen so sadly, it seems like the unique solution.
But, I don't think it is good enought to just fix it in this module, as @ThomasBinsfeld said, the bug is the same with the mandate, and I guess potentially other modules.
We can't do this hack in all modules, or else it will be so performance greedy with several of the concerned modules installed...

**Comment by rousseldenis** [comment] 2019-07-23 08:13
There is a PR on odoo to help overriding here : https://github.com/odoo/odoo/pull/31529

It has to be fixed.

**Comment by rousseldenis** [comment] 2019-07-23 08:34
Fixed.

@florian-dacosta @pedrobaeza @sebalix Could you review it ?

**Comment by florian-dacosta** [comment] 2019-07-24 09:46
@rousseldenis Thanks to take the time to try to fix it.
Let's see if Odoo accepts the hook...

**Comment by i-vyshnevska** [comment] 2019-08-29 11:27
fixing pr is merged

**Comment by simahawk** [comment] 2019-09-03 10:16
@florian-dacosta bugfix is merged in odoo. This should unlock https://github.com/OCA/sale-workflow/pull/786 as well.

**Comment by florian-dacosta** [comment] 2019-09-04 12:38
@simahawk 
AFAIK, what was merged in Odoo was just a refactore, but there was no bug in Odoo.
The bug is in account_payment_sale and the refactore allow us to fix it.
So, now, we need to fix account_payment_sale and add a test to cover the failing use case.
It should be quite quick and easy to do, I don't really have time right now, but I'll see if I can do it in the next days/weeks...
In the worst case scenario, I'll do it during OCA days if nobody did this before!

**Comment by lmignon** [comment] 2019-09-09 09:40
fixed by #630

**Closed as completed** 2019-09-10 10:30 UTC
