### ISSUE TITLE
odoo.sh 16 Error in saving payment method

### ISSUE THREAD

**Issue by alivinci-admin** [OCA/bank-payment#1035] opened 2023-02-13 16:53 UTC
## Module
account_payment_mode

## Describe the bug
`RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1612, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 1809, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 459, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 439, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-294>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/addons/account/models/account_payment_method.py", line 28, in create
    if information.get('mode') == 'multi':
AttributeError: 'NoneType' object has no attribute 'get'

The above server error caused the following client error:
null`

## To Reproduce
**Affected versions**: 16.0.1.0.0

[Odoo---Payment-Methods.webm](https://user-images.githubusercontent.com/77531375/218520821-b6e4d1dd-4456-4998-a49b-81e3ebaafaac.webm)

**Expected behavior**
Possibility to save the payment method

**Comment by akshatakulkarni25** [comment] 2023-02-21 03:52
hey @alivinci-admin , can i work on this issue

**Comment by pedrobaeza** [comment] 2023-02-21 07:14
This has nothing to do with modules of this repository, so closing.

**Closed as completed by pedrobaeza** 2023-02-21 07:14 UTC
Labels: bug

**Comment by alivinci-admin** [comment] 2023-03-03 10:50
@akshatakulkarni25

> hey @alivinci-admin , can i work on this issue

hi
yes please.. could you take care of this issue?

**Comment by akshatakulkarni25** [comment] 2023-03-05 05:27
yes thank you

**Comment by akshatakulkarni25** [comment] 2023-03-10 07:30
hey @alivinci-admin but the issue is closed , how shall i proceed forward?
