### ISSUE TITLE
[9.0] Migration script failed on "account_payment_order" module

### ISSUE THREAD

**Issue by jcoux** [OCA/bank-payment#328] opened 2017-01-06 10:37 UTC
**Impacted versions:**

9.0

**Steps to reproduce:**

1- Have the module "account_payment_order" installed on version "9.0.1.1.0" (With by example the hash : 11fff3357e148c56f2b1a03b41f9749895c61859 )
2- Upgrade the source on last version "9.0.1.1.1" (With by example the hash : a8146e5b47c65fab39789f0267c3177dd17a0434 )
3- Update the module "account_payment_order"

**Current behavior:**

The update of module bugs.
The problem is the migration script merged on PR : https://github.com/OCA/bank-payment/pull/325

The error is :
2017-01-06 10:29:14,608 67 ERROR odoodb OpenUpgrade: relation "payment_order" does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 1103, in wrapped_function
    version)
  File "/opt/odoo/external-src/bank-payment/account_payment_order/migrations/9.0.1.1.1/pre-migration.py", line 75, in migrate
    openupgrade.rename_columns(env.cr, column_renames_account_payment)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 332, in rename_columns
    'ALTER TABLE "%s" RENAME "%s" TO "%s"' % (table, old, new,))
  File "/opt/odoo/src/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/src/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "payment_order" does not exist

**Expected behavior:**

The module is correctly updated.

**Bug reason :**

The migration script try to rename relation "payment.order" to "account.payment.order", but the relation "payment.order" doesn't exists in V9.
And on version "9.0.1.1.0" of module "account_payment_order", we already have the model "account.payment.order".

Thanks in advance.

**Comment by damdam-s** [comment] 2017-01-06 10:40
same here
cc @pedrobaeza  @sergio-teruel @tecnativa

**Comment by pedrobaeza** [comment] 2017-01-06 10:42
The problem is the version number on the migration script. Changing it.

**Comment by pedrobaeza** [comment] 2017-01-06 10:48
Fixed in https://github.com/OCA/bank-payment/commit/c4a230073c9711adff80b74088ee628e1f57cfda

**Closed as completed by pedrobaeza** 2017-01-06 10:48 UTC

**Comment by jcoux** [comment] 2017-01-06 11:02
@pedrobaeza : Thanks for the fix ! It's works now :)
